
plugins {
    id 'java-library'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

tasks.test {
    useJUnit() // JUnit 4
    testLogging {
        // 显示所有测试事件
        events "passed", "skipped", "failed"
        // 打印 System.out 和 System.err
        showStandardStreams = true
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
